In [1]:
import numpy as np

X = np.array([[1,1], [1,0], [0,1], [0,0]])

# Saídas desejadas        
y = np.array([0, 1, 1, 0])

# Número de neurônios na camada oculta
hidden_neurons = 4 

# Inicializa os pesos aleatórios da camada de entrada para a oculta
input_weights = np.random.uniform(-1, 1, (X.shape[1], hidden_neurons))

# Calcula os outputs da camada oculta
hidden_output = X.dot(input_weights) 

# Determina os pesos otimizados da camada oculta para a de saída
# através da pseudoinversa de Moore-Penrose 
output_weights = np.linalg.pinv(hidden_output).dot(y)

# Faz previsões nos dados de treinamento
predictions = hidden_output.dot(output_weights)

# Imprime os pesos e previsões
print("Pesos aleatórios iniciais:")
print(input_weights)
print("Pesos camada oculta-saída:") 
print(output_weights)
print("Previsões ELM:")
print(predictions)

Pesos aleatórios iniciais:
[[-0.98275064 -0.63539304  0.21515501 -0.23371957]
 [-0.99115812  0.47702851  0.5952739  -0.11540677]]
Pesos camada oculta-saída:
[-0.28038166 -0.03463743  0.11100742 -0.05089815]
Previsões ELM:
[0.66666667 0.33333333 0.33333333 0.        ]
