In [1]:
import numpy as np

# Entradas de treinamento
X = np.array([[1, 1, 1], 
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 0],  
              [0, 0, 1],
              [0, 1, 0],
              [1, 0, 0],
              [0, 0, 0]])

# Saídas desejadas        
y = np.array([1, 1, 1, 1, 1, 1, 1, 0])

# Número de neurônios na camada oculta
hidden_neurons = 4 

# Inicializa os pesos aleatórios da camada de entrada para a oculta
input_weights = np.random.uniform(-1, 1, (X.shape[1], hidden_neurons))

# Calcula os outputs da camada oculta
hidden_output = X.dot(input_weights) 

# Determina os pesos otimizados da camada oculta para a de saída
# através da pseudoinversa de Moore-Penrose 
output_weights = np.linalg.pinv(hidden_output).dot(y)

# Faz previsões nos dados de treinamento
predictions = hidden_output.dot(output_weights)

# Imprime os pesos e previsões
print("Pesos aleatórios iniciais:")
print(input_weights)
print("Pesos camada oculta-saída:") 
print(output_weights)
print("Previsões ELM:")
print(predictions)

Pesos aleatórios iniciais:
[[-0.13784528 -0.7503692   0.67067751 -0.36216755]
 [ 0.57833253 -0.48979936  0.36802257 -0.72531603]
 [ 0.7623656   0.31322479  0.96935264 -0.81680452]]
Pesos camada oculta-saída:
[ 0.09591476 -0.28146081  0.30579095 -0.26765171]
Previsões ELM:
[1.5 1.  1.  1.  0.5 0.5 0.5 0. ]
